parameters:
    - name: modulesVersion
      displayName: CCoE modules version
      type: string
      default: 0.46.*
    - name: productsVersion
      displayName: CCoE products version
      type: string
      default: 0.49.*

steps:
- task: UniversalPackages@0
  displayName: "Download modules"  # Download the modules bundle
  inputs:
    command: "download"
    downloadDirectory: "$(System.DefaultWorkingDirectory)/"  # Modules will be downloaded in the working directory, recommendation is to not modify this value
    feedsToUse: "internal"
    vstsFeed: "CCoE.CertifiedProducts"
    vstsFeedPackage: "modules"
    vstsPackageVersion: ${{ parameters.modulesVersion }}

- task: UniversalPackages@0
  displayName: "Download products" # Download the produts bundle
  inputs:
    command: "download"
    downloadDirectory: "$(System.DefaultWorkingDirectory)/"
    feedsToUse: "internal"
    vstsFeed: "CCoE.CertifiedProducts"
    vstsFeedPackage: "products"
    vstsPackageVersion: ${{ parameters.productsVersion }}

- task: DeleteFiles@1
  displayName: 'Delete build.artifactstagingdirectory for infrastructure'
  inputs:
    SourceFolder: '$(build.artifactstagingdirectory)'
    Contents: '**'

- task: CopyFiles@2
  displayName: 'Copy Infrastructure files to build.artifactstagingdirectory'
  inputs:
    SourceFolder: $(System.DefaultWorkingDirectory)/
    Contents: |
     modules/**
     products/**
     infra/terraform/**     
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: infra'
  inputs:
    ArtifactName: infra